repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-docstring-first
  - id: debug-statements
  - id: name-tests-test
    args: ['--django']  # aka test*.py pattern
  - id: detect-private-key
    exclude: ^.github
  - id: check-json
  - id: check-xml
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-symlinks
  - id: check-executables-have-shebangs

- repo: https://github.com/pycqa/flake8
  rev: 3.8.1
  hooks:
  - id: flake8
    name: flake8

- repo: https://github.com/asottile/pyupgrade
  rev: v2.4.3
  hooks:
  - id: pyupgrade

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    name: black-formatter
    language_version: python3
    args: [--line-length=79, --skip-string-normalization]
    exclude: >
      /(
        \.github|
        \.direnv|
        \.eggs|
        \.git|
        \.hg|
        \.mypy_cache|
        \.pytest_cache|
        \.nox|
        \.tox|
        \.venv|
        venv|
        \.svn|
        _build|
        pymatch/_constants.py|
        pymatch.egg-info|
        setup.cfg|
        secrets|
        README.md|
        buck-out|
        build|
        dist
      )/

- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.4
  hooks:
  - id: python-bandit-vulnerability-check
    name: secruity-check
    args: [-l, --recursive, -x, tests]
    files: .py$
    stages: [push]
