# DESCRIPTION: This is a Github actions workflow to trigger a Slack message
# after successful merge of integration tests; if direct push to master,
# no notification will be given

name: Unit Tests

on:
  push:
    branches:
      - main
      - testing

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-18.04  # toggle here for local testing via nektos::act

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Set up Python 3.7.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.11

    - name: Unit Test
      env:
        LC_ALL: C.UTF-8
      run: |

        set -e

        python -m pip install --upgrade pip --quiet
        pip install -e .[tests]

        pytest -sx pymatch/tests

    - name: Build Dockerfile
      run: |
        docker build \
          --file=tools/docker/Dockerfile \
          --tag=pymatch-${GITHUB_SHA::7} \
          --build-arg=EXTENSIONS= \
          .

    - name: Test Docker Container
      run: |
        set -e
        echo $'B,1234567890,32503,1234567890\nB,1138,31502,7500' \
        | docker run -i pymatch-${GITHUB_SHA::7}

# EOF
