# DESCRIPTION: This is a Github actions workflow to trigger a Slack message
# after successful merge of integration tests; if direct push to master,
# no notification will be given

name: Unit Tests

on:
  push:
    branches:
      - main
      - testing

jobs:
  unit-test:
    name: Unit Test
    timeout-minutes: 120
    runs-on: ubuntu-18.04  # toggle here for local testing via nektos::act

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Set up Python 3.7.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.11

    - name: Unit Test
      env:
        LC_ALL: C.UTF-8
      run: |

        python -m pip install --upgrade pip --quiet

        pip install -e .[tests]

        pytest -sx pymatch/tests
